### ISSUE TITLE
Odometry

### ISSUE THREAD

**Issue by ethanharjabrata** [brightonfrc/2023-offseason#29]
Creating the Inertial navigation system for the robot

**Comment by ethanharjabrata** [comment]
Please read this once you are done with learning java.
https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/kinematics/SwerveDriveOdometry.html

**Comment by WebCoder49** [comment]
We are likely to be using a swerve drivetrain. These links ([explanation of swerve drive](https://compendium.readthedocs.io/en/latest/tasks/drivetrains/swerve.html) and [odometry description](https://docs.wpilib.org/en/stable/docs/software/kinematics-and-odometry/swerve-drive-odometry.html)) may be useful.

**Comment by ethanharjabrata** [comment]
> Please read this once you are done with learning java. https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/kinematics/SwerveDriveOdometry.html

**Comment by ethanharjabrata** [comment]
Resolve why the SwerveDriveKinematics class is apparently undefined.
Nvm resolved it.

**Comment by Cubanos1** [comment]
Example code for how to use gyrocscope according to user guide of 'micro navigation sensor'
https://pdocs.kauailabs.com/navx-mxp/examples/

**Comment by 10jwang** [comment]
Overview of what we have to do:

1. Hardware Setup:
Ensure your robot is equipped with the necessary sensors and hardware, including an IMU, wheel encoders, and motors. You should also have a microcontroller or computer onboard to process data and control the robot.

2. Sensor Calibration:
Calibrate your IMU and odometry sensors to ensure accurate data. This involves adjusting for biases, scale factors, and alignment errors. Each sensor may have its own calibration procedure.

3. Sensor Data Fusion:
Combine data from the IMU and odometry to estimate the robot's pose (position and orientation) over time. Sensor fusion algorithms like Extended Kalman Filters (EKF) or sensor fusion libraries (e.g., Robot Operating System - ROS) can be used to integrate data from these sensors.

4. Mapping:
Create a map of the environment where the robot will navigate. This could be a pre-built map or a map created as the robot explores the environment (SLAM - Simultaneous Localization and Mapping).

5. Path Planning:
Implement a path planning algorithm that generates a path from point A to point B on the map. Common algorithms include A*, Dijkstra's, or Rapidly-exploring Random Trees (RRT).

6. Control System:
Develop a control system that translates the desired path into motor commands for your robot. This system will use feedback from the sensors (IMU and odometry) to adjust the robot's movement in real-time to follow the path accurately. PID controllers are commonly used for this purpose.

7. Waypoint Following:
Divide the planned path into waypoints and ensure your robot can navigate to each waypoint with precision. The IMU and odometry data can help with real-time corrections to stay on track.

8. Obstacle Avoidance:
Implement obstacle detection and avoidance mechanisms using additional sensors like ultrasonic or LIDAR, or by integrating this data with your IMU and odometry information.

9. Testing and Tuning:
Conduct extensive testing to ensure the robot can reliably move from point A to point B. Fine-tune your algorithms and parameters based on the robot's actual performance..

10. Integration and Communication:
Ensure that the control software can communicate with other systems or interfaces, as needed, to monitor the robot's progress or change its instructions in real time.

**Comment by ethanharjabrata** [comment]
Found the code to use the gyro:
https://docs.wpilib.org/en/stable/docs/software/hardware-apis/sensors/gyros-software.html
Scroll down to navX
Here is the java lib:
https://www.kauailabs.com/public_files/navx-mxp/apidocs/java/com/kauailabs/navx/frc/AHRS.html

**Comment by WebCoder49** [comment]
For your information, we are using a NavX2 MXP gyroscope. Sorry if I didn't make this clear.

**Comment by WebCoder49** [comment]
Offseason task
