### ISSUE TITLE
Dist. Sensor

### ISSUE THREAD

**Issue by SophiaNass** [brightonfrc/2023-offseason#30]

**Comment by ahe127** [comment]
https://maxbotix.com/pages/lv-maxsonar-ez-datasheet

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 04 October 2023 16:18
To: ***@***.***>
Cc: Allen ***@***.***>; ***@***.***>
Subject: [brightonfrc/2023-offseason] Dist. Sensor (Issue #30)

**Comment by WebCoder49** [comment]
Offseason task
