### ISSUE TITLE
Color sensor

### ISSUE THREAD

**Issue by 09lkei** [brightonfrc/2023-offseason#32]

**Comment by WebCoder49** [comment]
We are likely to be using [the REV Robotics Color Sensor V3](https://www.revrobotics.com/rev-31-1557/).

**Comment by 09lkei** [comment]
@SunnyP448 @11cgodwin Please have a look at [this documentation](https://codedocs.revrobotics.com/java/com/revrobotics/colorsensorv3) to see how the color sensor works in code

**Comment by WebCoder49** [comment]
Offseason task
